# GCC compiler
CC=g++

# compilation flags (none)
LDFLAGS=

# source file
SOURCE=./square_sum.cpp

# binary name
EXEC=square_sum.exe

all:
	$(CC) $(LDFLAGS) $(SOURCE) -o $(EXEC)
	@echo -e "----- COMPILATION DONE -----"

clean:
	rm -r $(EXEC)